# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - "status:idea"
  - "status:planning"
  - "status:on hold"
  - "status:ready"
  - "type:bug"
  - "type:docs"
  - "type:enhancement"
  - "type:feature"
  - "type:refactor"
  - "type:task"

# Label to use when marking an issue as stale
staleLabel: "status:stale"

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit to only `issues` or `pulls`
only: issues
